# TP Régression

Ce TP a pour principe de manipuler les outils de numpy et scipy vu en cours. Les différentes seront aussi optimisée avec Cython et Numba pour faire des comparaisons.

In [0]:
import numpy as np
import scipy as sp
import scipy.linalg as spl

## Question 1 : Générateur de matrice aléatoire
Construire une fonction construisant une matrice de taille $m \times n$ dont les valeurs sont tirées selon une loi normal de variance $\sigma^2$, i.e. $M \in \mathcal{M}(m,n)$ et $\forall i\ M[i, :] \sim \mathcal{N}(0,\sigma^2 \mathrm{I})$.

In [0]:
def generate_mat(m, n, sigma):
    """
    Generate a random matrix using a Gaussian distribution of variance $\sigma^2$

    Parameters
    ----------
    m: int
        The number of lines
    n: int
        The number of columns
    sigma: float
        The square root of the variance

    Returns
    -------
    The generated matrix
    """
    mat = np.random.normal(size=(m, n), scale=sigma)
    return mat

In [0]:
size = 1000

In [0]:
A = generate_mat(10000, size, 1.)

In [0]:
A

array([[-0.96053711,  0.49517288, -0.16032626, ...,  0.07474089,
         0.85403129, -0.0665458 ],
       [ 0.33180509,  1.17430432, -1.00942108, ..., -1.54423726,
        -0.71515862,  0.29398399],
       [ 0.74604581, -1.29452979,  1.67140953, ..., -2.04227451,
         0.27968613,  1.21698234],
       ..., 
       [ 0.30541441, -0.09507129, -1.0176184 , ...,  0.59265773,
         1.17073779,  0.4755666 ],
       [-0.41527108, -2.02988448,  0.83261627, ..., -1.04774143,
        -0.13359921,  0.34741891],
       [ 1.26724455, -1.81631798,  1.59481415, ...,  0.75129624,
        -0.30688551,  0.72863356]])

## Question 2 : Conditionnement de la matrice $A$
Le conditionnement d'une matrice se calcule en faisant le rapport entre sa plus grande singulière propre et sa plus petite. Quel est donc le conditionnement de la matrice $A$ ?

In [0]:
(u, s, vh) = np.linalg.svd(A)

In [0]:
s[0:10]

array([ 131.18601469,  130.85398585,  130.66457738,  130.48364293,
        130.20385107,  130.15402939,  129.89341104,  129.68677556,
        129.56961986,  129.45460022])

In [0]:
max(s) / min(s)

1.9171651924254547

Nous pouvons aussi utiliser la fonction *cond* de Numpy.

In [0]:
np.linalg.cond(A)

1.9171651924254525

## Question 3 : Un petit problème de regression
Prendre un vecteur $x$, calculer $b = Ax$ puis utiliser les outils d'algèbre linéaire de numpy et scipy pour retrouver $x$. Lequel est le plus rapide ?

In [0]:
x = np.zeros(size)
x[0:10] = 2

In [0]:
b = np.dot(A, x)

In [0]:
%timeit np.linalg.lstsq(A, b)
xest = np.linalg.lstsq(A, b)

793 ms ± 6.34 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [0]:
xest[0]

array([  2.00000000e+00,   2.00000000e+00,   2.00000000e+00,
         2.00000000e+00,   2.00000000e+00,   2.00000000e+00,
         2.00000000e+00,   2.00000000e+00,   2.00000000e+00,
         2.00000000e+00,   9.43689571e-16,  -1.66533454e-16,
         5.55111512e-16,   7.49400542e-16,  -3.88578059e-16,
         1.16573418e-15,   5.55111512e-16,  -9.71445147e-16,
         1.08246745e-15,  -1.33226763e-15,  -1.80411242e-15,
        -1.38777878e-16,   1.47104551e-15,  -1.56819002e-15,
        -8.32667268e-17,  -4.99600361e-16,   1.08246745e-15,
         8.60422844e-16,  -1.30451205e-15,  -1.06858966e-15,
         8.74300632e-16,  -1.19348975e-15,  -1.22124533e-15,
        -7.77156117e-16,   4.02455846e-16,   1.60982339e-15,
        -1.81799020e-15,  -2.77555756e-16,  -6.93889390e-16,
         2.02615702e-15,   1.38777878e-17,  -1.47104551e-15,
        -1.16573418e-15,   4.16333634e-17,   2.08166817e-16,
         6.17561557e-16,  -9.99200722e-16,  -7.77156117e-16,
        -1.72084569e-15,

In [0]:
xest2 = spl.lstsq(A, b)
%timeit spl.lstsq(A, b)

843 ms ± 69.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [0]:
xest2[0]

array([  2.00000000e+00,   2.00000000e+00,   2.00000000e+00,
         2.00000000e+00,   2.00000000e+00,   2.00000000e+00,
         2.00000000e+00,   2.00000000e+00,   2.00000000e+00,
         2.00000000e+00,   9.43689571e-16,  -1.66533454e-16,
         5.55111512e-16,   7.49400542e-16,  -3.88578059e-16,
         1.16573418e-15,   5.55111512e-16,  -9.71445147e-16,
         1.08246745e-15,  -1.33226763e-15,  -1.80411242e-15,
        -1.38777878e-16,   1.47104551e-15,  -1.56819002e-15,
        -8.32667268e-17,  -4.99600361e-16,   1.08246745e-15,
         8.60422844e-16,  -1.30451205e-15,  -1.06858966e-15,
         8.74300632e-16,  -1.19348975e-15,  -1.22124533e-15,
        -7.77156117e-16,   4.02455846e-16,   1.60982339e-15,
        -1.81799020e-15,  -2.77555756e-16,  -6.93889390e-16,
         2.02615702e-15,   1.38777878e-17,  -1.47104551e-15,
        -1.16573418e-15,   4.16333634e-17,   2.08166817e-16,
         6.17561557e-16,  -9.99200722e-16,  -7.77156117e-16,
        -1.72084569e-15,

## Question 4 : Descente de gradient
Nous allons faire notre propre méthode pour le calcul de la solution. Pour cela nous allons utiliser une descente de gradient dont le schéma est le suivant,
\begin{equation*}
x_{t+1} = x_t - \mu A'(A x_t - b)
\end{equation*}
avec $\mu$ le pas de descente et $x_0 = 0$ pour commencer. Un critère d'arrêt est de considéré la différence entre deux itérations successives et s'arrêter si celle-ci est trop faible, ici nous allons regarder,
\begin{equation*}
\frac{\|x_{t+1} - x_t\|}{\|x_{t+1}\|} < \tau
\end{equation*}
où $\tau$ est la tolérance.

Note : pour éviter des boucles infinies, il faut utiliser une boucle *for* avec un grand nombre d'itérations.

In [0]:
def solver(a, b, mu, tau):
    """
    Solve $ax = b$ using a gradient descent scheme.
    
    Parameters
    ----------
    a: np.ndarray
        A (m x n) matrix
    b: np.ndarray
        A vector of size n
    mu: float
        The descent step
    tau: float
        The tolerance (stopping criterion)
    """
    xt = np.zeros(a.shape[1])
    for i in range(5000):
        xtt = xt - mu * np.dot(a.T, np.dot(a, xt) - b)
        if tau > np.linalg.norm(xtt - xt)/np.linalg.norm(xtt):
            xt = xtt
            break
        xt = xtt
    return xt

In [0]:
xest3 = solver(A, b, 0.0001, 1e-15)

In [0]:
xest3

array([  2.00000000e+00,   2.00000000e+00,   2.00000000e+00,
         2.00000000e+00,   2.00000000e+00,   2.00000000e+00,
         2.00000000e+00,   2.00000000e+00,   2.00000000e+00,
         2.00000000e+00,   3.91757859e-17,  -1.92798541e-17,
         4.44788140e-17,  -9.03670278e-17,  -7.02247943e-17,
         4.66225767e-17,  -3.61777502e-17,   8.07458221e-17,
        -1.48111797e-18,  -1.26287754e-16,  -8.23572505e-17,
        -3.07700772e-17,   1.33075085e-17,  -1.53863522e-16,
        -2.04874447e-17,   2.69846142e-17,  -3.39641668e-17,
        -2.61550897e-17,  -4.81726571e-17,  -4.09322001e-17,
         2.36047300e-17,  -4.12603862e-17,   5.85404487e-17,
         3.78412459e-17,  -6.56131066e-17,  -5.57433652e-17,
         2.53683403e-17,   6.34073396e-17,  -5.45759645e-17,
         1.23501601e-17,  -4.75102999e-17,  -5.27663780e-17,
         6.58339044e-18,  -2.15058459e-17,  -4.10786107e-18,
        -1.46986444e-16,  -6.14188073e-17,  -2.53483533e-17,
         3.72143520e-17,

Comparons maintenant le temps de calcul.

In [0]:
%timeit solver(A, b, 0.0001, 1e-15)

748 ms ± 6.07 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## Question 5 : Optimisation du code avec Cython et Numba
Construire deux fonctions reprenant le code précédent et en utilisant Cython puis Numba pour accélérer le code.

In [0]:
%load_ext Cython

In [0]:
%%cython
import numpy as np
cimport numpy as np

def solver_cython(np.ndarray[double, ndim=2] a not None,
                  np.ndarray[double, ndim=1] b not None, double mu, double tau):
    """
    Solve $ax = b$ using a gradient descent scheme.
    
    Parameters
    ----------
    a: np.ndarray
        A (m x n) matrix
    b: np.ndarray
        A vector of size n
    mu: float
        The descent step
    tau: float
        The tolerance (stopping criterion)
    """
    cdef np.ndarray[double, ndim=1] xt = np.zeros(a.shape[1])
    cdef np.ndarray[double, ndim=1] xtt = np.zeros(a.shape[1])
    cdef int i = 0
    for i in range(5000):
        xtt = xt - mu * np.dot(a.T, np.dot(a, xt) - b)
        if tau > np.linalg.norm(xtt - xt)/np.linalg.norm(xtt):
            xt = xtt
            break
        xt = xtt
    return xt

In [0]:
%timeit solver_cython(A, b, 0.0001, 1e-15)

801 ms ± 103 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [0]:
xest4 = solver_cython(A, b, 0.0001, 1e-15)

In [0]:
xest4

array([  2.00000000e+00,   2.00000000e+00,   2.00000000e+00,
         2.00000000e+00,   2.00000000e+00,   2.00000000e+00,
         2.00000000e+00,   2.00000000e+00,   2.00000000e+00,
         2.00000000e+00,   3.91757859e-17,  -1.92798541e-17,
         4.44788140e-17,  -9.03670278e-17,  -7.02247943e-17,
         4.66225767e-17,  -3.61777502e-17,   8.07458221e-17,
        -1.48111797e-18,  -1.26287754e-16,  -8.23572505e-17,
        -3.07700772e-17,   1.33075085e-17,  -1.53863522e-16,
        -2.04874447e-17,   2.69846142e-17,  -3.39641668e-17,
        -2.61550897e-17,  -4.81726571e-17,  -4.09322001e-17,
         2.36047300e-17,  -4.12603862e-17,   5.85404487e-17,
         3.78412459e-17,  -6.56131066e-17,  -5.57433652e-17,
         2.53683403e-17,   6.34073396e-17,  -5.45759645e-17,
         1.23501601e-17,  -4.75102999e-17,  -5.27663780e-17,
         6.58339044e-18,  -2.15058459e-17,  -4.10786107e-18,
        -1.46986444e-16,  -6.14188073e-17,  -2.53483533e-17,
         3.72143520e-17,

In [0]:
import numba

In [0]:
solver_numba = numba.jit(solver)

In [0]:
%timeit solver_numba(A, b, 0.0001, 1e-15)

740 ms ± 3.75 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [0]:
xest5 = solver_numba(A, b, 0.0001, 1e-15)

In [0]:
xest5

array([  2.00000000e+00,   2.00000000e+00,   2.00000000e+00,
         2.00000000e+00,   2.00000000e+00,   2.00000000e+00,
         2.00000000e+00,   2.00000000e+00,   2.00000000e+00,
         2.00000000e+00,   3.91757859e-17,  -1.92798541e-17,
         4.44788140e-17,  -9.03670278e-17,  -7.02247943e-17,
         4.66225767e-17,  -3.61777502e-17,   8.07458221e-17,
        -1.48111797e-18,  -1.26287754e-16,  -8.23572505e-17,
        -3.07700772e-17,   1.33075085e-17,  -1.53863522e-16,
        -2.04874447e-17,   2.69846142e-17,  -3.39641668e-17,
        -2.61550897e-17,  -4.81726571e-17,  -4.09322001e-17,
         2.36047300e-17,  -4.12603862e-17,   5.85404487e-17,
         3.78412459e-17,  -6.56131066e-17,  -5.57433652e-17,
         2.53683403e-17,   6.34073396e-17,  -5.45759645e-17,
         1.23501601e-17,  -4.75102999e-17,  -5.27663780e-17,
         6.58339044e-18,  -2.15058459e-17,  -4.10786107e-18,
        -1.46986444e-16,  -6.14188073e-17,  -2.53483533e-17,
         3.72143520e-17,

## Question 6 : Plus loin avec Cython
Numba fait mieux que Cython. Essayons d'améliorer le code Cython en évitant au maximum les appels aux fonctions *numpy*.
Pour cela il faut réécrire le calcul de la norme euclidienne et les produits matriciels. Pour cela nous allons,
- utiliser les *memory views* pour avoir un accès directe aux valeurs,
- réduire au maximum les allocations de mémoire.

In [0]:
%%cython
import numpy as np
cimport numpy as np
cimport cython


@cython.boundscheck(False) # turn off bounds-checking for entire function
@cython.wraparound(False)  # turn off negative index wrapping for entire function
cdef double norm(double [:] x, int length):
    """
    Compute the Euclidean norm of the vector
    
    Parameters
    ----------
    x: np.ndarray
        The vector
        
    Returns
    -------
    The norm of $x$.
    """
    cdef double sum = 0.
    cdef int i = 0
    for i in range(length):
        sum += x[i] * x[i]
    return np.sqrt(sum)

@cython.boundscheck(False) # turn off bounds-checking for entire function
@cython.wraparound(False)  # turn off negative index wrapping for entire function
def solver_cython2(np.ndarray[double, ndim=2] a not None, np.ndarray[double, ndim=1] b not None, double mu, double tau):
    """
    Solve $ax = b$ using a gradient descent scheme.
    
    Parameters
    ----------
    a: np.ndarray
        A (m x n) matrix
    b: np.ndarray
        A vector of size n
    mu: float
        The descent step
    tau: float
        The tolerance (stopping criterion)
    """
    cdef np.ndarray[double, ndim=1] xt = np.zeros(a.shape[1])
    cdef np.ndarray[double, ndim=1] xtt = np.zeros(a.shape[1])
    cdef np.ndarray[double, ndim=1] res = np.zeros(a.shape[0])
    cdef np.ndarray[double, ndim=1] diff = np.zeros(a.shape[1])
    
    cdef int lines = a.shape[0]
    cdef int cols = a.shape[1]
    
    cdef double [ :, : ] a_view = a
    cdef double [ : ] xt_view = xt
    cdef double [ : ] xtt_view = xtt
    cdef double [ : ] res_view = res
    cdef double [ : ] b_view = b
    cdef double [ : ] diff_view = diff
    
    cdef int i = 0
    cdef int line = 0
    cdef int col = 0
    
    cdef double tmp = 0.
    
    for i in range(5000):

        for line in range(lines):
            tmp = 0.
            for col in range(cols):
                tmp += a_view[line, col] * xt_view[col]
            res_view[line] = tmp - b_view[line]

        for col in range(cols):
            tmp = 0.
            for line in range(lines):
                tmp += a_view[line, col] * res_view[line]
            xtt_view[col] = xt_view[col] - mu * tmp
            diff_view[col] = xtt_view[col] - xt_view[col]

        if tau > norm(diff_view, cols)/norm(xtt_view, cols):
            for col in range(cols):
                xt_view[col] = xtt_view[col]
            break

        for col in range(cols):
            xt_view[col] = xtt_view[col]
            
    return xt

In [0]:
%timeit solver_cython2(A, b, 0.0001, 1e-15)

5.92 s ± 147 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [0]:
xest5 = solver_cython2(A, b, 0.0001, 1e-15)

In [0]:
xest5

array([  2.00000000e+00,   2.00000000e+00,   2.00000000e+00,
         2.00000000e+00,   2.00000000e+00,   2.00000000e+00,
         2.00000000e+00,   2.00000000e+00,   2.00000000e+00,
         2.00000000e+00,  -2.23886830e-17,   4.00398686e-17,
         1.75797881e-17,  -3.67589588e-17,  -4.98709004e-17,
         6.52582736e-17,  -3.80590064e-17,   3.08181064e-17,
        -7.84188828e-19,  -3.40913567e-17,  -2.71064931e-17,
        -8.08620183e-17,  -3.93498943e-18,  -7.06055951e-17,
        -3.41287900e-17,   2.89461549e-17,  -2.99631161e-17,
        -6.04715530e-17,  -3.47969426e-17,   1.00829324e-17,
        -3.51960260e-17,  -1.16661669e-16,   5.35277072e-17,
        -2.46448239e-17,   1.18089407e-17,   7.03549142e-18,
         5.47702841e-17,   4.36481429e-17,   5.90171140e-17,
         6.47840486e-17,   5.98966315e-18,   5.86203867e-17,
         7.64040211e-17,  -4.23467374e-17,   5.99908105e-17,
        -5.24966595e-17,  -7.76477951e-17,  -1.44257643e-17,
         5.46187827e-17,

## Question 7 : Jouons un peu avec la parcimonie
Le vecteur que nous utilisons est parcimonieux, c'est à dire qu'il est composé majoritairement de zéros. Nous pouvons en profiter pour améliorer l'estimation. Pour cela, nous allons utiliser le seuillage doux itératif, dont le schéma pour un nombre scalaire est le suivant,
\begin{equation*}
x_{t+1} = \mathrm{ST}_{\mu\lambda}(x_t - \mu A'(A x_t - b))
\end{equation*}
avec $\mathrm{ST}_{\lambda}$ l'opérateur de seuillage doux de paramètre $\lambda$, $\mu$ le pas de descente et $x_0 = 0$ pour commencer. L'opérateur de seuillage doux est défini de la façon suivante,
\begin{equation*}
\mathrm{ST}_{\lambda} : x \mapsto \begin{cases} 0, &\text{ si } |x| \le \lambda,\\
(|x|-\lambda)sign(x), &\text{sinon}. \end{cases}
\end{equation*}

Le critère d'arrêt est de nouveau la différence entre deux itérations successives et s'arrêter si celle-ci est trop faible, ici nous allons regarder,
\begin{equation*}
\frac{\|x_{t+1} - x_t\|}{\|x_{t+1}\|} < \tau
\end{equation*}
où $\tau$ est la tolérance.

**(1)** Commençons par construire le seuillage doux 

In [0]:
def soft_thresholding(x, thresh):
    """
    Soft thresholding operator
    
    Parameters
    ----------
    x: np.ndarray
        The input vector
    thresh: double
        The threshold
    """
    res = np.zeros(x.shape[0])
    ax = np.abs(x)
    ix = ax >= thresh
    res[ix] = (ax[ix] - thresh)*np.sign(x[ix])
    return res

**(2)** Construisons un nouveau solver

In [0]:
def sparse_solver(a, b, mu, tau, thresh):
    """
    Solve $ax = b$ using a gradient descent scheme.
    
    Parameters
    ----------
    a: np.ndarray
        A (m x n) matrix
    b: np.ndarray
        A vector of size n
    mu: double
        The descent step
    tau: double
        The tolerance (stopping criterion)
    thresh: double
        The threshold at each iteration i.e. the equilibrium parameter
    Returns
    -------
    The estimate at convergence.
    """
    xt = np.zeros(a.shape[1])
    for i in range(5000):
        xtt = soft_thresholding(xt - mu * np.dot(a.T, np.dot(a, xt) - b), thresh*mu)
        if tau > np.linalg.norm(xtt - xt)/np.linalg.norm(xtt):
            xt = xtt
            break
        xt = xtt
    return xt

In [0]:
xest6 = sparse_solver(A, b, 0.0001, 1e-15, 0.05)

In [0]:
xest6

array([ 1.99999478,  1.99999499,  1.99999512,  1.99999518,  1.99999501,
        1.99999507,  1.99999489,  1.99999469,  1.9999947 ,  1.99999518,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.  

Regardons la vitesse...

In [0]:
%timeit sparse_solver(A, b, 0.0001, 1e-15, 0.05)

247 ms ± 25.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


**(3)** Amélioration du seuillage doux en construisant une fonction universelle

In [0]:
def soft_thresholding_single(x, thresh):
    """
    Soft thresholding operator
    
    Parameters
    ----------
    x: np.ndarray
        The input vector
    thresh: double
        The threshold
    """
    if x > thresh:
        return x-thresh
    elif x < -thresh:
        return x+thresh
    return 0
soft_thresholding2 = np.vectorize(soft_thresholding_single)

In [0]:
def sparse_solver2(a, b, mu, tau, thresh):
    """
    Solve $ax = b$ using a gradient descent scheme.
    
    Parameters
    ----------
    a: np.ndarray
        A (m x n) matrix
    b: np.ndarray
        A vector of size n
    mu: double
        The descent step
    tau: double
        The tolerance (stopping criterion)
    thresh: double
        The threshold at each iteration i.e. the equilibrium parameter
    Returns
    -------
    The estimate at convergence.
    """
    xt = np.zeros(a.shape[1])
    for i in range(5000):
        xtt = soft_thresholding2(xt - mu * np.dot(a.T, np.dot(a, xt) - b), thresh*mu)
        if tau > np.linalg.norm(xtt - xt)/np.linalg.norm(xtt):
            xt = xtt
            break
        xt = xtt
    return xt

In [0]:
%timeit sparse_solver2(A, b, 0.0001, 1e-15, 0.05)

242 ms ± 6.35 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Nous pouvons faire encore mieux en utilisant Numba.

In [0]:
soft_thresholding3 = numba.vectorize(soft_thresholding_single)

In [0]:
def sparse_solver3(a, b, mu, tau, thresh):
    """
    Solve $ax = b$ using a gradient descent scheme.
    
    Parameters
    ----------
    a: np.ndarray
        A (m x n) matrix
    b: np.ndarray
        A vector of size n
    mu: double
        The descent step
    tau: double
        The tolerance (stopping criterion)
    thresh: double
        The threshold at each iteration i.e. the equilibrium parameter
    Returns
    -------
    The estimate at convergence.
    """
    xt = np.zeros(a.shape[1])
    for i in range(5000):
        xtt = soft_thresholding3(xt - mu * np.dot(a.T, np.dot(a, xt) - b), thresh*mu)
        if tau > np.linalg.norm(xtt - xt)/np.linalg.norm(xtt):
            xt = xtt
            break
        xt = xtt
    return xt

In [0]:
%timeit sparse_solver3(A, b, 0.0001, 1e-15, 0.05)

232 ms ± 6.01 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Conclusion ?